runtime: nodejs14
service: url-shortener
env_variables:
  NODE_ENV:
  CONNECTION_URI:
  BASE_URL:
  PORT:
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.8
